### PR TITLE
Fixed Deprecation Warnings

### PR DESCRIPTION
**Pull request by Txus5012**
Hi. This PR fixes the deprecation warnings commented [here](https://github.com/pplans/foundry-vtt-module-motion-tracker/pull/58).

I also added "Dead" to the default "Statuses settings".

### CODE REVIEW

**Comment by pplans** [comment]
Hi can you move the PR to target the dev branch ? Main is only used for release and stable versions if not it seems ok besides the context Alpha

**Comment by Txus5012** [comment]
I'm not sure if I can do that. I can close this one and re-send it to dev.

About useContextAlpha, it isn't needed because it was false anyway. I can add the non-deprecated equivalents if you want.
Here is how it looks now:
Motion

**Comment by pplans** [comment]
Actually I don't know either how to do that, but if you wanna contribute I'd suggest to checkout the dev branch and PR in there, you'll get the newest things. I can't start accepting PRs on main sorry (plus I'd prefer you do this because you fixed the issue so that you'd get the credit of it)

**Comment by Txus5012** [comment]
OK.

**Pull request closed without merging**
